nuevo secreto

diff --git a/.github/workflows/create-pr-for-deploy.yml b/.github/workflows/create-pr-for-deploy.yml
--- a/.github/workflows/create-pr-for-deploy.yml
+++ b/.github/workflows/create-pr-for-deploy.yml
@@ -82,6 +82,37 @@ jobs:
                        --body "Deployment triggered by ${{ github.actor }}" \
                        --head ${{ steps.create-branch.outputs.branch_name }}
 
+      - name: Get Pull Request ID
+        id: pr-id
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+              sleep 5  # Espera para asegurar que el PR esté registrado
+          
+              # Intentar obtener el ID del PR con reintentos
+              max_retries=5
+              retry_delay=3
+              attempt=0
+              pr_id=""
+          
+              while [[ -z "$pr_id" && $attempt -lt $max_retries ]]; do
+                pr_id=$(gh pr list --state open --head ${{ steps.create-branch.outputs.branch_name }} --json number -q '.[0].number')
+                
+                if [[ -z "$pr_id" ]]; then
+                  echo "Pull request ID not found. Retrying in $retry_delay seconds..."
+                  sleep $retry_delay
+                  ((attempt++))
+                fi
+              done
+          
+              if [[ -z "$pr_id" ]]; then
+                echo "❌ ERROR: Could not retrieve Pull Request ID after multiple attempts."
+                exit 1
+              fi
+          
+              echo "Pull Request ID: $pr_id"
+              echo "pr_id=$pr_id" >> $GITHUB_ENV
+
       - name: Approve and Review Pull Request using API
         if: ${{ env.qa_values_changed == 'true' }}
         env:
